# Generated by Django 5.2.3 on 2025-08-31 15:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва категорії')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва курсу')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(verbose_name='Опис')),
                ('short_description', models.CharField(max_length=300, verbose_name='Короткий опис')),
                ('image', models.ImageField(blank=True, null=True, upload_to='courses/', verbose_name='Зображення')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ціна')),
                ('difficulty', models.CharField(choices=[('beginner', 'Початковий'), ('intermediate', 'Середній'), ('advanced', 'Просунутий')], max_length=20, verbose_name='Складність')),
                ('duration_hours', models.PositiveIntegerField(default=0, verbose_name='Тривалість (години)')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубліковано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.category')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курси',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата запису')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершення')),
                ('progress', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Прогрес (%)')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Запис на курс',
                'verbose_name_plural': 'Записи на курси',
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва уроку')),
                ('slug', models.SlugField()),
                ('content', models.TextField(blank=True, verbose_name='Зміст')),
                ('video_url', models.URLField(blank=True, verbose_name='Посилання на відео')),
                ('lesson_type', models.CharField(choices=[('video', 'Відео'), ('text', 'Текст'), ('quiz', 'Тест'), ('assignment', 'Завдання')], max_length=20, verbose_name='Тип уроку')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('duration_minutes', models.PositiveIntegerField(default=0, verbose_name='Тривалість (хвилини)')),
                ('is_free', models.BooleanField(default=False, verbose_name='Безкоштовний урок')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['order'],
                'unique_together': {('course', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оцінка')),
                ('comment', models.TextField(blank=True, verbose_name='Коментар')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Відгук',
                'verbose_name_plural': 'Відгуки',
                'unique_together': {('course', 'student')},
            },
        ),
    ]
